{% set name = "file-tree-fsl" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/file-tree-fsl-{{ version }}.tar.gz
  sha256: 29a057f6a34fe2ec61e66756f34c4a8cbd068a9095b81fe03634cf44188bd247

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - file-tree
    - python >={{ python_min }}

test:
  imports:
    - file_tree_fsl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.fmrib.ox.ac.uk/ndcn0236/file-tree-fsl
  summary: Filetree definitions for the FSL neuroimaging library
  license: MIT
  license_file: LICENSE
  doc_url: https://open.win.ox.ac.uk/pages/ndcn0236/file-tree

extra:
  recipe-maintainers:
    - MichielCottaar
